### ISSUE TITLE
Verzia 1.3.0 vôbec nejde

### ISSUE THREAD

**Issue by karci78** [kodi-czsk/plugin.video.sosac.ph#113]
Ahojte...včera som aktualizoval na verziu 1.3.0 vo win 7 aj androide kodi 16.1 a po aktualizacii sa nikde okrem vyhladávania nikde nedostanem...kde kolvek kliknem,vždy chyba doplnku...

08:23:36 T:6480  NOTICE: DVDPlayer: finished waiting
08:23:44 T:5244  NOTICE: ['URL: ?cp=736f7361632e7068&list=687474703a2f2f6d6f766965732e7072656872616a2e6d65']
08:23:44 T:5244  NOTICE: ["Running sosac provider with params: {'cp': 'sosac.ph', 'list': 'http://movies.prehraj.me'}"]
08:23:44 T:5244  NOTICE: ["Initializing provider sosac.ph with settings {'lang': '0', 'downloads': '', 'quality': '0', 'subs': True}"]
08:23:44 T:5244  NOTICE: ['Examining url http://movies.prehraj.me']
08:23:44 T:5244   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\default.py", line 47, in <module>
                                                XBMCSosac(SosacContentProvider(reverse_eps=reverse_eps), settings, __addon__).run(params)
                                              File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\contentprovider\xbmcprovider.py", line 82, in run
                                                self.list(self.provider.list(params['list']))
                                              File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 202, in list
                                                return self.list_videos(url)
                                              File "C:\Users\Kajo\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 218, in list_videos
                                                json_video_array = json.loads(data)
                                              File "C:\Moje programy\Kodi\system\python\Lib\json\__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Moje programy\Kodi\system\python\Lib\json\decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Moje programy\Kodi\system\python\Lib\json\decoder.py", line 384, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
08:23:44 T:6480   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=687474703a2f2f6d6f766965732e7072656872616a2e6d65
08:23:44 T:6480   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=687474703a2f2f6d6f766965732e7072656872616a2e6d65) failed

Neviem či vám toto pomôže,je to pár spodných riadkov logu.

**Comment by karci78** [comment]
Pomohlo vymazanie cache...ak by mal niekdo podobný problém...sorry za obťažovanie...

**Comment by Saljack** [comment]
Rekl bych, ze soubory nebyly dostupne (jestli to bylo vsude) ale to spis varim z vody (vcera jsem videl chyby pri otvirani u sebe taky). Je dost mozne, ze sosac nestiha ty jsony "servirovat".  Zkus to prosim jeste dnes. Pokud by to neslo zapni prosim debug logging v Kodi
`Settings -> System -> Logging -> Enable debug logging`
parkrat nekam klikni v sosaci a nahraj sem cely log.
