### ISSUE TITLE
Nefunkční stahování 

### ISSUE THREAD

**Issue by DrazekV** [kodi-czsk/plugin.video.sosac.ph#146]
Od doby nutnosti použít přihlášení přestalo fungovat korektně stažení. Vždy se stáhne jen několik málo kB nefunkčního souboru. 

Jen dodám, že nefunguje se zaplaceným a přihlášeným účtem.

**Comment by ghost** [comment]
ide stiahnuť v chrome? so zaplateným účtom? pomocou developer tools network?

**Comment by DrazekV** [comment]
To ano v chrome mám i doplněk co to umí. Ovšem přes kodi doplněk to nejde. V tabletu jsem vždy dal před delší cestou stáhnout pár pohádek a bylo. Což teď nejde.

**Comment by ghost** [comment]
rozumiem ok tak to potom teoreticky pojde... len ma to zaujimalo dik

**Comment by Saljack** [comment]
Ahoj, ted jsem zkousel stahovani a me funguje. Mohl by to jeste nekdo overit a pripadne zavrit?

**Comment by lzoubek** [comment]
U me taky funguje, zaviram

**Comment by hruspeter** [comment]
Zdravim,
  u mne nefunguje taky - presne z dovodu popsanych: @DrazekV .
Mam Raspberry 4, Raspbian 10, kodi 18.7, nejnovejsi sosac.
( Na Kodi: 17, ale download funguje bez problemu.)

Chyba z logu (kodi.log):
2020-09-05 20:11:53.442 T:2596045008   ERROR: Traceback (most recent call last):                                                                                                                                                             
2020-09-05 20:11:53.442 T:2596045008   ERROR:   File "/home/pi/.kodi/addons/script.module.stream.resolver/lib/xbmcutil.py", line 490, in download                                                                                            
2020-09-05 20:11:53.444 T:2596045008   ERROR:     opener.retrieve(remote, local, reporthook=self.dlProgress)                                                                                                                                 
2020-09-05 20:11:53.444 T:2596045008   ERROR:   File "/usr/lib/python2.7/urllib.py", line 283, in retrieve                                                                                                                                   
2020-09-05 20:11:53.455 T:2596045008   ERROR:     reporthook(blocknum, bs, size)                                                                                                                                                             
2020-09-05 20:11:53.455 T:2596045008   ERROR:   File "/home/pi/.kodi/addons/script.module.stream.resolver/lib/xbmcutil.py", line 514, in dlProgress                                                                                          
2020-09-05 20:11:53.455 T:2596045008   ERROR:     self.callback(percent, speed, est, self.filename)                                                                                                                                          
2020-09-05 20:11:53.455 T:2596045008   ERROR:   File "/home/pi/.kodi/addons/script.module.stream.resolver/lib/xbmcutil.py", line 445, in callback                                                                                            
2020-09-05 20:11:53.455 T:2596045008   ERROR:     24042) % percent + ' - %s KB/s %s' % (speed, esTime)                                                                                                                                       
2020-09-05 20:11:53.456 T:2596045008   ERROR: ValueError: incomplete format                                                                                                                                                                  

Nasel jsem tohle: https://www.xbmc-kodi.cz/prispevek-soubory-online?page=2 
- jako workaround by melo fungovat: "že v nastavení pluginu zakážu zobrazení průběhu stahování."

Ten samy problem jsem mel i se starsim Raspbianem na kodi 0.18. Verze 0.17 fungovala taky bez problemu.

Dekuji

**Comment by milankosk** [comment]
nefunguje...skusal som a nejde stahovat :(
