### ISSUE TITLE
Sosac Error

### ISSUE THREAD

**Issue by marfuschka** [kodi-czsk/plugin.video.sosac.ph#151]
Ahoj, asi 2 tyzdne mam problem so sosacom. Najprv prestal prehravat videa a teraz sa uz ani nespusti a hodi chybu hned po nastartovani kodi. 
Raspberry Pi2 
open elec 8.8.4
krypton 17.3
sosac 1.3.7

**log po nastartovani kodi** (hadam citatelny, som rada, ze som ho nejak vyhrabala ;) )
```
11:34:49.555 T:1729328032 ERROR: ## OpenELEC Addon ## oe::load_url(http://update.openelec.tv/updates.php?i=4d3663a46916f9b3a2c07f2762b88 
) ## ERROR: (CertifcateError(“hostname ‘update.openelec.tv’ doesn‘t match either of 'analytics.openelec.tv‘, 'diskuss.openelec.tv’, www1.openelec.tv’”,))
11:34:49.559 T:1729328032 ERROR: Traceback (most recent call last); 

File ”/home/stepha/projects/openelec-8.0git/build.OpenELEC-RPi2.arm8.0.44/OpenELEC-settings line 270, in load_url 
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen 
File "/usr/lib/python2.7/urllib2.py", line 435, in open 
File "/usr/lib/python2.7/urllib2.py", line 548, in http_response 
File "/usr/lib/python2.7/urllib2.py", line 467, in error 
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain 
File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302 
File "/usr/lib/python2.7/urllib2.py", line 429, in open 
File "/usr/lib/python2.7/urllib2.py", line 447, in _open 
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain 
File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open 
File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open 
File "/usr/lib/python2.7/httplib.py", line 1042, in request 
File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders 
File "/usr/lib/python2.7/httplib.py", line 882, in _send_output 
File "/usr/lib/python2.7/httplib.py", line 844, in send 
File "/usr/lib/python2.7/httplib.py", line 1263, in connect 
File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket 
FIle "/usr/lib/python2.7/ssl.py", line 611, in _init_ 
File "/usr/lib/python2.7/ssl.py", line 848, in do_handshake 
File "/usr/lib/python2.7/ssl.py", line 282, in match_hostname 

CertificateError: hostname 'update.openelec.tv' doesn‘t match either of 'analytics.openelec.tv', 'diskuss.openelec.tv', 'www1.openelec.tv' 

11:34:49.567 T:1729328032 ERROR: ## OpenELEC Addon ## system::check_updates_v2 ## ERROR: (TypeError(‘expected string or buffer',)) 
11:34:49.569 T:1729328032 ERROR: Traceback (most recent call last): 
File "/home/stephan/projects/openelec-8.0.git/build.OpenELEC-RPi2.arm-8.0.4/OpenELEC-settings line 538, In check_updates_v2 
File "/usr/lib/python2.7/json/_init_.py‘, line 339, in loads 
File "/usr/Iib/python2.7ljson/decoder.py", line 364, in decode 
TypeError: expected string or buffer 
-------------------------------------------------------------------------------------------------------------------
```
**log pri pokuse spustit add-on**
```
11:36:28.738 T:1947267088 ERROR: GetDirectory - Error getting plugin://plugin. video. sosac.ph/ 
11:36:28.740 T:1947267088 ERROR:
CGUIMediaWindow::GetDirectory(plugIn://plugin.video.sosac.ph/) failed 
------------------------------------------------------------------------
11:36:02.004 T:1406813088 ERROR: Previous line repeats 6 times. 
11:36:02.004 T21406813088 ERROR: EXCEPTION Thrown (PythonToCppException) : ->Python callback/script returned the following error<--

- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! 
Error Type: <type 'exceptions.NameError'> 
Error Contents: global name 'self' is not defined 
Traceback (most recent call last): 
File "/storage/.kodi/addons/plugin.video.sosac.ph/default.py', line 26, in <module> 
from resources.lib.sosac import SosacContentProvider 
File "storage/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py“, line 32, in <module>  from provider import ContentProvider, cached, ResolveException 
File "storage/.kodi/addons/script.module.stream.resolver/lib/contentprovider/provider.py”, line 27, in <module> import StorageServer
File "/storage/.kodi/addons/script.commom.plugin.cache/Iib/StorageServer.py", line 764, in <module> checkInstanceMode() 
File "/storage/.kodi/addons/script.commom.plugin.cache/Iib/StorageServer.py", line 755, in checkInstanceMode
self.xbmc.log(u" StorageServer Module loaded RUN(instance only)") 
NameError: global name 'self' is not defined 

-->End of script error report<-
```

**Comment by jose1711** [comment]
skusil by som preinstalovat sosaca i jeho zavislosti, teda:
* script.module.stream.resolver
* script.common.plugin.cache

**Comment by marfuschka** [comment]
Jo je to v tom. Na inštaláciu sosacu treba v configuracii "Common plugin cache" addone vypnúť "Autostart with XMBC" ale potom to zas treba naspäť zapnúť. Chjo ... Dik za pomoc :)

**Comment by jose1711** [comment]
No zrejme tam bude este nejaky iny problem, ale zavieram ako "works for me".
