### ISSUE TITLE
Sosac nejde spustit

### ISSUE THREAD

**Issue by j-mak** [kodi-czsk/plugin.video.sosac.ph#162]
Caute, od vcera (22.9.2018) mi nejde spustit sosac. Ked ho spustim tak mi zahlasi sosac chybu a viac mam vraj v denniku udalosti (log?). 

Zapol som logovanie a spustil znova, v logoch sa mi objavilo:

```13:14:44.488 T:2760721152   ERROR: EXCEPTION Thrown (PythonToCppException) : 
  -->Python callback/script returned the following error<--
   - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.TypeError'>
  Error Contents: cannot concatenate 'str' and 'NoneType' objects
  Traceback (most recent call last):
    File "/home/osmc/.kodi/addons/plugin.video.sosac.ph/default.py", line 56, in <module>
      XBMCSosac(sosac, settings, __addon__).run(params)
    File "/home/osmc/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 80, in run
      return self.root()
    File "/home/osmc/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 160, in root
      self.list(self.provider.categories())
    File "/home/osmc/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 192, in categories
      item = self.item_with_last_mod("TV Shows - Recently added", URL + J_TV_SHOWS_RECENTLY_ADDED)
    File "/home/osmc/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 512, in item_with_last_mod
      lastmod = self.request_last_update(url)
    File "/home/osmc/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 508, in request_last_update
      util.debug('last update' + lastmod)
  TypeError: cannot concatenate 'str' and 'NoneType' objects
  -->End of Python script error report<--
```

skusal som uz aj aktualizaciu a reinstall, nepomohlo.

**Comment by Saljack** [comment]
Co se ti zobrazí po zadání adresy http://tv.sosac.to/vystupy5981/tvshowsrecentlyadded.json ? Vypadá to, že nepřišla hlavička Last-Modified. Odstranil jsem tedy debug hlášku a mělo by to začít fungovat zkus si tam nahrát verzi z mého repa https://github.com/Saljack/plugin.video.sosac.ph/tree/patch-1 a dej vědět zda to pomohlo.

**Comment by j-mak** [comment]
Pravdepodobne toto neni bug/problem v sosaci (pretestujem a dam vediet). Ked som spravil request na tu http tak som dostal 403 na proxy (nemal som ziadnu proxy) a mensim skumanim som zistil ze moj router bol napadnuty. Vycistil som to a poskusam/ozvem sa ci to uz chodi alebo nie.
