### ISSUE TITLE
Nejde spustit plugin

### ISSUE THREAD

**Issue by m1l4n89** [kodi-czsk/plugin.video.sosac.ph#172]
Čau,
mám Raspberry Pi 2 používal jsem Kodi 18.7 se starší verzí pluginu a vše fungovalo. Včera jsem udělal aktualizaci na Kodi 19 a aktualizaci pluginu na verzi 1.4.1 . Po aktualizaci se plugin nespustí. 

Koukal jsem do logů a končí to chybou:
2022-04-06 13:43:02.794 T:2270     INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-04-06 13:43:02.795 T:2270     INFO <general>: CAESinkALSA::Initialize - Attempting to open device "default"
2022-04-06 13:43:02.819 T:2270     INFO <general>: CAESinkALSA::Initialize - Opened device "default"
2022-04-06 13:43:02.822 T:2270     INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2022-04-06 13:43:02.822 T:2270     INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S16NE
2022-04-06 13:43:07.234 T:2690     INFO <general>: initializing python engine.
2022-04-06 13:43:22.299 T:2690     INFO <general>: ['URL: ']
2022-04-06 13:43:22.302 T:2690     INFO <general>: ['Running sosac provider with params: {}']
2022-04-06 13:43:22.325 T:2690     INFO <general>: ["Initializing provider sosac.ph with settings {'downloads': '', 'quality': '0', 'subs': True, 'lang': '0'}"]
2022-04-06 13:43:23.141 T:2690    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: time data 'Wed, 06 Apr 2022 04:36:29 GMT' does not match format '%a, %d %b %Y %H:%M:%S %Z'
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/plugin.video.sosac.ph/default.py", line 56, in <module>
                                                       XBMCSosac(sosac, settings, __addon__).run(params)
                                                     File "/home/pi/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 81, in run
                                                       return self.root()
                                                     File "/home/pi/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 161, in root
                                                       self.list(self.provider.categories())
                                                     File "/home/pi/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 176, in categories
                                                       item = self.item_with_last_mod("Movies - Recently added", URL + J_MOVIES_RECENTLY_ADDED)
                                                     File "/home/pi/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 512, in item_with_last_mod
                                                       lastmod = self.request_last_update(url)
                                                     File "/home/pi/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 502, in request_last_update
                                                       lastmodtime = time.strptime(response.info().get_all('Last-Modified')[0],
                                                     File "/usr/lib/python3.9/_strptime.py", line 562, in _strptime_time
                                                       tt = _strptime(data_string, format)[0]
                                                     File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
                                                       raise ValueError("time data %r does not match format %r" %
                                                   ValueError: time data 'Wed, 06 Apr 2022 04:36:29 GMT' does not match format '%a, %d %b %Y %H:%M:%S %Z'
                                                   -->End of Python script error report<--

2022-04-06 13:43:23.564 T:2690     INFO <general>: Python interpreter stopped
2022-04-06 13:43:23.582 T:2688    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.sosac.ph/
2022-04-06 13:43:23.596 T:2186    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sosac.ph/) failed

Zkoušel jsem plugin odinstalovat a nainstalovat znovu a stejná chyba.

Nemáte někdo radu co s tím?

Předem dík

**Comment by Saljack** [comment]
Nainstaluj z https://repo.xbmc-kodi.cz/

**Comment by m1l4n89** [comment]
Původní verze na Kodi 18 byla z **https://kodi-czsk.github.io/repository/** , ale tam již nebyla podpora. Takže současnou verzi již mám právě z repozitáře **https://repo.xbmc-kodi.cz/**.

**Comment by m1l4n89** [comment]
Provedl jsem i úplně čistou instalaci Kodi 19. A pořád stejné. To vypadá možná na nějakou novější verzi PYTHONa a má to problém se syntaxí. Nemůže být problém v tom formátu datumu?

**Comment by zajdee** [comment]
Pokud nainstalujete OSMC v poslední verzi a nastavíte regionální nastavení na češtinu, dojde k nastavení systémového locale Pythonu na CZ.

Chyba vypadá krypticky, protože uvedený datum/čas v default locale Python naparsuje.
```
ValueError: time data 'Mon, 21 Nov 2022 16:36:29 GMT' does not match format '%a, %d %b %Y %H:%M:%S %Z'
```

Jakmile ale použijete lang CZ, očekává český zkrácený název dne a měsíce, např. `Po, 21 lis 2022 16:19:41`. A ten se samozřejmě naparsovat nepovede, protože v HTTP hlavičce je datum anglicky. Řešením je pro parsovací funkci dočasně předefinovat locale, např. takto:
```
--- sosac.py.orig	2022-11-21 22:36:23.875308293 +0100
+++ sosac.py	2022-11-21 22:36:09.305272367 +0100
@@ -23,6 +23,7 @@
 import urllib.request, urllib.parse, urllib.error
 import http.cookiejar
 import hashlib
+import locale
 import sys
 import json
 import datetime
@@ -499,8 +500,11 @@
         req.add_header('User-Agent', util.UA)
         try:
             response = urllib.request.urlopen(req)
+            saved_locale = locale._setlocale(locale.LC_TIME)
+            locale.setlocale(locale.LC_TIME, 'C')
             lastmodtime = time.strptime(response.info().get_all('Last-Modified')[0],
                 '%a, %d %b %Y %H:%M:%S %Z')
+            locale.setlocale(locale.LC_TIME, saved_locale)
             lastmod = datetime.datetime(*lastmodtime[:6]).strftime('%d.%m.%Y')
             response.close()
         except urllib.error.HTTPError as error:
```
