### ISSUE TITLE
Přidání do knihovny a odběry nefunkční v Kodi Matrix

### ISSUE THREAD

**Issue by sikysikov** [kodi-czsk/plugin.video.sosac.ph#173]
V KODI Matrix a v doplňku verze 1.4.1 nejde přidávat položky do knihovny, tzv. "Add to Library" v kontextové nabídce. Zároveň nejdou tzv. odběry např. u Seriálů. Vyhazuje to Python chyby:

> EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'in <string>' requires string as left operand, not int
                                                   Traceback (most recent call last):
                                                     File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\default.py", line 56, in <module>
                                                       XBMCSosac(sosac, settings, __addon__).run(params)
                                                     File "C:\Users\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\contentprovider\xbmcprovider.py", line 98, in run
                                                       return self.run_custom(params)
                                                     File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sutils.py", line 274, in run_custom
                                                       self.add_item(item)
                                                     File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sutils.py", line 172, in add_item
                                                       nfo_file = os.path.join(item_dir, self.normalize_filename(
                                                     File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sutils.py", line 48, in normalize_filename
                                                       return ''.join(c for c in cleanedFilename if c in validFilenameChars)
                                                     File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sutils.py", line 48, in <genexpr>
                                                       return ''.join(c for c in cleanedFilename if c in validFilenameChars)
                                                   TypeError: 'in <string>' requires string as left operand, not int
                                                   -->End of Python script error report<--

**Comment by sikysikov** [comment]
Bump... nedokáže někdo opravit, aby šlo v KODI MATRIX přidávat filmy ze SOSÁČe do knihovny?
