### ISSUE TITLE
Problem s pluginom pri prehravani

### ISSUE THREAD

**Issue by bzuc0** [kodi-czsk/plugin.video.sosac.ph#34]
Ahoj,

mam problem s pluginom, akonahle chcem vyhladat alebo kliknut na kategoriu vyhodi mi chybu. Pridavam log pre viac info:

```
18:01:10 T:4456  NOTICE: Thread LanguageInvoker start, auto delete: false
18:01:10 T:4456  NOTICE: -->Python Interpreter Initialized<--
18:01:10 T:4456  NOTICE: ('URL: ', '?cp=736f7361632e7068&search-list=23')
18:01:10 T:4456  NOTICE: ('Running sosac provider with params:', {'search-list': '#', 'cp': 'sosac.ph'})
18:01:10 T:4456  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': '', 'quality': '0', 'subs': True}"]
18:01:10 T:5476  NOTICE: Thread BackgroundLoader start, auto delete: false
18:01:13 T:268  NOTICE: Thread JobWorker start, auto delete: true
18:01:13 T:1688  NOTICE: Thread LanguageInvoker start, auto delete: false
18:01:13 T:1688  NOTICE: -->Python Interpreter Initialized<--
18:01:13 T:1688  NOTICE: ('URL: ', '?cp=736f7361632e7068&search=7374617a69737469')
18:01:13 T:1688  NOTICE: ('Running sosac provider with params:', {'search': 'stazisti', 'cp': 'sosac.ph'})
18:01:13 T:1688  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': '', 'quality': '0', 'subs': True}"]
18:01:13 T:1688   ERROR: ['Unable to parse convert addon setting to number']
18:01:15 T:1688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'httplib.IncompleteRead'>
                                            Error Contents: IncompleteRead(3392 bytes read)
                                            Traceback (most recent call last):
                                              File "C:\Users\Bzuco\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\default.py", line 48, in <module>
                                                XBMCSosac(SosacContentProvider(reverse_eps=reverse_eps),settings,**addon**).run(params)
                                              File "C:\Users\Bzuco\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\contentprovider\xbmcprovider.py", line 74, in run
                                                return self.do_search(params['search'])
                                              File "C:\Users\Bzuco\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\contentprovider\xbmcprovider.py", line 124, in do_search
                                                self.search(what)
                                              File "C:\Users\Bzuco\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\contentprovider\xbmcprovider.py", line 205, in search
                                                self.list(self.provider.search(keyword))
                                              File "C:\Users\Bzuco\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 87, in search
                                                urllib.urlencode({'q': keyword})))
                                              File "C:\Users\Bzuco\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 432, in list_search
                                                html_tree = self.parse_html(url)
                                              File "C:\Users\Bzuco\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 428, in parse_html
                                                return BeautifulSoup(util.request(url))
                                              File "C:\Users\Bzuco\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\util.py", line 83, in request
                                                data = response.read()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\socket.py", line 351, in read
                                                data = self._sock.recv(rbufsize)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\httplib.py", line 543, in read
                                                return self._read_chunked(amt)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\httplib.py", line 597, in _read_chunked
                                                raise IncompleteRead(''.join(value))
                                            IncompleteRead: IncompleteRead(3392 bytes read)
                                            -->End of Python script error report<--
18:01:15 T:7800   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&search=7374617a69737469
18:01:15 T:7800   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&search=7374617a69737469) failed
18:01:15 T:7152  NOTICE: Thread LanguageInvoker start, auto delete: false
18:01:15 T:7152  NOTICE: -->Python Interpreter Initialized<--
18:01:15 T:7152  NOTICE: ('URL: ', '?cp=736f7361632e7068&search-list=23')
18:01:15 T:7152  NOTICE: ('Running sosac provider with params:', {'search-list': '#', 'cp': 'sosac.ph'})
18:01:15 T:7152  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': '', 'quality': '0', 'subs': True}"]
18:01:15 T:7720  NOTICE: Thread BackgroundLoader start, auto delete: false﻿
```

**Comment by lzoubek** [comment]
log je z vyhledani, kdy se zda, ze doslo k preruseni spojeni se serverem `Error Contents: IncompleteRead(3392 bytes read)` musela to byt chyba na serveru nebo po ceste. Vyhledavani nyni funguje.

**Comment by bzuc0** [comment]
Stale bez zmeny. Aj ostatne pluginy su na tom podobne. Jedine co funguje je genesis
