### ISSUE TITLE
Nelze otevřít seriál Bionická žena

### ISSUE THREAD

**Issue by tprochazka** [kodi-czsk/plugin.video.sosac.ph#47]
Při pokusu rozkliknout seriál Bionická žena dokjde k následující chybě:

```
22:30:20 T:11632   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=23747673686f7723687474703a2f2f74762e7072656872616a2e6d652f63732f64657461696c2f62696f6e69636b612d7a656e61
22:30:20 T:11632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=23747673686f7723687474703a2f2f74762e7072656872616a2e6d652f63732f64657461696c2f62696f6e69636b612d7a656e61) failed
22:30:22 T:4312  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': 'D:\\\\Filmy\\\\', 'quality': '1', 'subs': True}"]
22:30:22 T:4312   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: unknown url type: #tvshow
                                            Traceback (most recent call last):
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\default.py", line 48, in <module>
                                                XBMCSosac(SosacContentProvider(reverse_eps=reverse_eps),settings,__addon__).run(params)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\contentprovider\xbmcprovider.py", line 65, in run
                                                self.list(self.provider.list(params['list']))
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 187, in list
                                                return self.list_tv_shows_by_letter(url)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 458, in list_tv_shows_by_letter
                                                shows = self.list_by_letter(url)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 288, in list_by_letter
                                                page = self.get_data_cached(url)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\contentprovider\provider.py", line 220, in wrap
                                                return cache.cacheFunction(f, *args)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.common.plugin.cache\lib\StorageServer.py", line 570, in cacheFunction
                                                ret_val = funct(*args)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 284, in get_data_cached
                                                return util.request(url)
                                              File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\util.py", line 84, in request
                                                response = urllib2.urlopen(req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 396, in open
                                                protocol = req.get_type()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 258, in get_type
                                                raise ValueError, "unknown url type: %s" % self.__original
                                            ValueError: unknown url type: #tvshow
                                            -->End of Python script error report<--
22:30:22 T:11632   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=23747673686f7723687474703a2f2f74762e7072656872616a2e6d652f63732f64657461696c2f62696f6e69636b612d7a656e61
22:30:22 T:11632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=23747673686f7723687474703a2f2f74762e7072656872616a2e6d652f63732f64657461696c2f62696f6e69636b612d7a656e61) failed

```

**Comment by tprochazka** [comment]
Díky moc, funguje to!
