### ISSUE TITLE
Automatické aktualizace strm

### ISSUE THREAD

**Issue by iChUdY** [kodi-czsk/plugin.video.sosac.ph#49]
Nějak mě ve verzi 1.2.5 nefunguje automatická aktualizace knihovny po přidání nových strm. 
Automatické přidávání strm nových dílů seriálů také nefunguje. 
Chybová hláška je klasika 💃 

Je to vlastnost verze 1.2.5 nebo je problém u mě? 
čisté instalace: rpi 2 openelec 6.03(kodi 15), rpi2 libreelec(kodi 17)

**Comment by sprattek** [comment]
Mam rovnaky problem s verziou 1.2.7, ked dam cez sosac "Add all to library", do kniznice nic nove nepribudne.

**Comment by petrm74** [comment]
Poslední verze doplňku je 1.2.8. Automatická aktualizace pro přidání nových dílů seriálů funguje normálně. Add all to library také funguje správně, problém bude v nastavení pluginu, nebo ve scraperu. Více informací na fóru http://www.xbmc-kodi.cz/forum-sosac

**Comment by iChUdY** [comment]
Automatická aktualizace... Fungovala jen pár dní. Nyní to vždy hodí chybu a nefunguje.

**Comment by lubo** [comment]
@iChUdY Aku chybu ?

**Comment by petrm74** [comment]
iChUdY: Mě to tedy žádnou chybu na RPi2 s OpenElec 6.0.3 nehází.

**Comment by zbyna** [comment]
Pravděpodobně se jedná o následující chybu:
ale pozor číslo řádku  `\resources\lib\sutils.py", line 99`   je o 4 řádky posunuté kvůli mým úpravám, které přidávájí
 `3 řádky komentářů` 
 a jeden `from myPlayer import mujPlayer`  kde mujPlayer implementuje callbacks pro eventy xbmc.player - takže se do subscription neplete - předpokládám  :smile:

```
19:26:43 T:1416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "C:\Users\decak\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\service.py", line 38, in <module>
                                                XBMCSosac(SosacContentProvider(reverse_eps=reverse_eps), settings, __addon__).service()
                                              File "C:\Users\decak\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sutils.py", line 69, in service
                                                self.evalSchedules()
                                              File "C:\Users\decak\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sutils.py", line 99, in evalSchedules
                                                refresh = int(sub['refresh'])
                                            TypeError: string indices must be integers, not str
                                            -->End of Python script error report<--
19:26:43 T:5344   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
```

```
19:16:17 T:5344  NOTICE: Starting Kodi (16.1 Git:20160424-c327c53). Platform: Windows NT x86 32-bit
19:16:17 T:5344  NOTICE: Using Release Kodi x32 build
```

**Comment by iChUdY** [comment]
Ahoj,

Chyba se projevuje když mám v subscription více jak jeden seriál.

Vyzkoušeno např. na seriálech Narcos, Preacher:

- pokud mám v subscribtion jen seriál Narcos, tak chyba nenastane

- pokud mám v subscribtion jen seriál Prearcher, tak chyba nenastane

- pokud mám v subscribtion oba dva seriály, tak chyba nastane

Tímto postupem jsem zkoušel i jiný seriály a vzorec je stejný. Pokud mám v subscribtion více jak jeden seriál, tak nastane chyba a subscribtion není funkční. 

Vyzkoušeno na čistých instalacích pouze s addonem Sosáč.

**LOG KODI 15.2**

> -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/service.py", line 38, in <module>
                                                XBMCSosac(SosacContentProvider(reverse_eps=reverse_eps), settings, __addon__).service()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/resources/lib/sutils.py", line 65, in service
                                                self.evalSchedules()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/resources/lib/sutils.py", line 95, in evalSchedules
                                                refresh = int(sub['refresh'])
                                            TypeError: string indices must be integers, not str
                                            -->End of Python script error report<--

**LOG KODI 16.1**

> -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'dict' object has no attribute 'encode'
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/service.py", line 38, in <module>
                                                XBMCSosac(SosacContentProvider(reverse_eps=reverse_eps), settings, __addon__).service()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/resources/lib/sutils.py", line 65, in service
                                                self.evalSchedules()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/resources/lib/sutils.py", line 108, in evalSchedules
                                                'refresh': sub['refresh']
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/resources/lib/sutils.py", line 224, in run_custom
                                                if self.add_item(params):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/resources/lib/sutils.py", line 153, in add_item
                                                item_url = util._create_plugin_url(arg, 'plugin://' + self.addon_id + '/')
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.stream.resolver/lib/util.py", line 149, in _create_plugin_url
                                                value = value.encode('ascii', 'ignore')
                                            AttributeError: 'dict' object has no attribute 'encode'
                                            -->End of Python script error report<--

**LOG KODI 17b1**

> -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/service.py", line 38, in <module>
                                                XBMCSosac(SosacContentProvider(reverse_eps=reverse_eps), settings, __addon__).service()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/resources/lib/sutils.py", line 65, in service
                                                self.evalSchedules()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.sosac.ph/resources/lib/sutils.py", line 95, in evalSchedules
                                                refresh = int(sub['refresh'])
                                            TypeError: string indices must be integers, not str
                                            -->End of Python script error report<--

**Comment by iChUdY** [comment]
Ahoj,

ano jedná se o tuto chybu. Založil jsem nový issue..
