### ISSUE TITLE
android import problem

### ISSUE THREAD

**Issue by janpal** [kodi-czsk/plugin.video.sosac.ph#60]
ahojte 
pocase mi sosac zblbne na mojom android tv boxe.
ak pozrem kodi.log vidim ze python prestal resolvovat importy.
pomoze reinstall kodi. pouzivam kodi 16.1
neskor sa problem opat objavi a vtedy prestanu fungovat aj ostatne pluginy ako napr. befun.cz

00:21:36 T:2011294512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named util
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sosac.ph/service.py", line 24, in <module>
                                                from resources.lib.sosac import SosacContentProvider
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 30, in <module>
                                                import util
                                            ImportError: No module named util
                                            -->End of Python script error report<--
00:22:21 T:2005166840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named util
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.befun.cz/default.py", line 24, in <module>
                                                import befun
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.befun.cz/resources/lib/befun.py", line 24, in <module>
                                                import util,resolver
                                            ImportError: No module named util
                                            -->End of Python script error report<--
00:22:22 T:1977547872   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.befun.cz/
00:22:22 T:1977547872   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.befun.cz/) failed
00:22:27 T:2067530664   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named util
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.markiza.sk/default.py", line 26, in <module>
                                                import markiza
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.markiza.sk/resources/lib/markiza.py", line 31, in <module>
                                                import util
                                            ImportError: No module named util
                                            -->End of Python script error report<--
00:22:27 T:1977547872   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.markiza.sk/
00:22:27 T:1977547872   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.markiza.sk/) failed

aky log mam este  prilozit?

**Comment by jose1711** [comment]
`util.py` je poskytovany doplnkom script.module.stream.resolver. ak pise chybu, tak by som skontroloval, ci adresar s tymto doplnkom niekam "nezmizol"
