### ISSUE TITLE
Sosac KODI repo error in SONY BRAVIA ANDROID

### ISSUE THREAD

**Issue by okioki13** [kodi-czsk/plugin.video.sosac.ph#91]
Hi, my SOSAC KODI in sony bravia kdl-65w855c is reporting error for tv shows 
Below are the messages from event log.
Any idea?

```
22:37:11 T:18446744072361618320  NOTICE: special://profile/ is mapped to: special://masterprofile/
22:37:11 T:18446744072361618320  NOTICE: -----------------------------------------------------------------------
22:37:11 T:18446744072361618320  NOTICE: Starting Kodi (16.1 Git:2016-04-24-f6ceced). Platform: Android ARM 32-bit
22:37:11 T:18446744072361618320  NOTICE: Using Release Kodi x32 build
22:37:11 T:18446744072361618320  NOTICE: Kodi compiled Apr 24 2016 by GCC 4.8.0 for Android ARM 32-bit API level 17 (API level 17)
22:37:11 T:18446744072361618320  NOTICE: Running on Sony BRAVIA 2015 with Android 5.1.1 API level 22, kernel: Linux ARM 32-bit version 3.10.27
22:37:11 T:18446744072361618320  NOTICE: FFmpeg version: 2.8.6-kodi-2.8.6-Jarvis-16.0
22:37:11 T:18446744072361618320  NOTICE: Host CPU: ARMv7 Processor rev 0 (v7l), 2 cores available
22:37:11 T:18446744072361618320  NOTICE: Product: SVPDTV15_EU, Device: SVP-DTV15, Board: SVPDTV15 - Manufacturer: Sony, Brand: Sony, Model: BRAVIA 2015, Hardware: mt5890
22:37:11 T:18446744072361618320  NOTICE: External storage path = /storage/emulated/0; status = ok
22:37:11 T:18446744072361618320  NOTICE: ARM Features: Neon enabled
22:37:11 T:18446744072361618320  NOTICE: special://xbmc/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
22:37:11 T:18446744072361618320  NOTICE: special://xbmcbin/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
22:37:11 T:18446744072361618320  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
22:37:11 T:18446744072361618320  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
22:37:11 T:18446744072361618320  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
22:37:11 T:18446744072361618320  NOTICE: The executable running is:
22:37:11 T:18446744072361618320  NOTICE: Local hostname: localhost
22:37:11 T:18446744072361618320  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
22:37:11 T:18446744072361618320  NOTICE: -----------------------------------------------------------------------
22:37:11 T:18446744072361618320  NOTICE: load settings...
22:37:11 T:18446744072361618320   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
22:37:12 T:18446744072361618320 WARNING: CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
22:37:12 T:18446744072361618320   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
22:37:12 T:18446744072361618320   DEBUG: AESinkAUDIOTRACK - 44100 supported
22:37:12 T:18446744072361618320   DEBUG: AESinkAUDIOTRACK - 48000 supported
22:37:12 T:18446744072361618320   DEBUG: AESinkAUDIOTRACK - 96000 supported
22:37:12 T:18446744072361618320  NOTICE: Found 1 Lists of Devices
22:37:12 T:18446744072361618320  NOTICE: Enumerated AUDIOTRACK devices:
22:37:12 T:18446744072361618320  NOTICE:     Device 1
22:37:12 T:18446744072361618320  NOTICE:         m_deviceName      : AudioTrack
22:37:12 T:18446744072361618320  NOTICE:         m_displayName     : android
22:37:12 T:18446744072361618320  NOTICE:         m_displayNameExtra: audiotrack
22:37:12 T:18446744072361618320  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
22:37:12 T:18446744072361618320  NOTICE:         m_channels        : FL,FR,FC,LFE,BL,BR,SL,SR
22:37:12 T:18446744072361618320  NOTICE:         m_sampleRates     : 48000,44100,48000,96000
22:37:12 T:18446744072361618320  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_AC3,AE_FMT_DTS
22:37:12 T:18446744072361618320   DEBUG: CSkinSettings: no <skinsettings> tag found
22:37:12 T:18446744072361618320  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
22:37:12 T:18446744072361618320  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
22:37:12 T:18446744072361618320  NOTICE: Default DVD Player: dvdplayer
22:37:12 T:18446744072361618320  NOTICE: Default Video Player: dvdplayer
22:37:12 T:18446744072361618320  NOTICE: Default Audio Player: paplayer
22:37:12 T:18446744072361618320  NOTICE: Disabled debug logging due to GUI setting. Level 0.
22:37:12 T:18446744072361618320  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
22:37:12 T:18446744072361618320  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
22:37:12 T:18446744072361618320  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
22:37:12 T:18446744072361618320  NOTICE: Loaded playercorefactory configuration
22:37:12 T:18446744072361618320  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
22:37:12 T:18446744072361618320  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
22:37:12 T:18446744072361618320  NOTICE: Running database version Addons20
22:37:12 T:18446744072361618320  NOTICE: ADDONS: Using repository repository.xbmc.org
22:37:12 T:18446744072361618320  NOTICE: ADDONS: Using repository repository.tknorris.release
22:37:12 T:18446744072361618320  NOTICE: ADDONS: Using repository superrepo.kodi.helix.all
22:37:12 T:18446744072361618320  NOTICE: ADDONS: Using repository repository.beam.xbmc-addons
22:37:12 T:18446744072361618320  NOTICE: ADDONS: Using repository repository.xbmchub
22:37:12 T:18446744072361618320  NOTICE: ADDONS: Using repository repository.kodi-czsk
22:37:12 T:18446744072361618320  NOTICE: virtual bool CWinSystemEGL::InitWindowSystem(): Using EGL Implementation: android
22:37:12 T:18446744072361618320  NOTICE: CEGLNativeTypeAndroid: Switching to resolution:
22:37:12 T:18446744072361618320  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
22:37:12 T:18446744072361618320  NOTICE: Previous line repeats 1 times.
22:37:12 T:18446744072361618320  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000004 Hz
22:37:12 T:18446744072361618320  NOTICE: Found (1920x1080@60.000004) at 16, setting to RES_DESKTOP at 16
22:37:12 T:18446744072361618320  NOTICE: Checking resolution 16
22:37:12 T:18446744072361618320  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
22:37:12 T:18446744072361618320  NOTICE: CEGLNativeTypeAndroid: Switching to resolution: 1920x1080 @ 60.00 - Full Screen
22:37:12 T:18446744072361618320  NOTICE: GL_VENDOR = ARM
22:37:12 T:18446744072361618320  NOTICE: GL_RENDERER = Mali-T624
22:37:12 T:18446744072361618320  NOTICE: GL_VERSION = OpenGL ES 3.1
22:37:12 T:18446744072361618320  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.10
22:37:12 T:18446744072361618320  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic
22:37:12 T:18446744072361618320  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
22:37:12 T:18446744072361618320  NOTICE: Running database version Addons20
22:37:12 T:18446744072361618320  NOTICE: Running database version ViewModes6
22:37:12 T:18446744072361618320  NOTICE: Running database version Textures13
22:37:12 T:18446744072361618320  NOTICE: Running database version MyMusic56
22:37:12 T:18446744072361618320  NOTICE: Running database version MyVideos99
22:37:12 T:18446744072361618320  NOTICE: Running database version TV29
22:37:12 T:18446744072361618320  NOTICE: Running database version Epg11
22:37:13 T:18446744072361618320 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
22:37:13 T:18446744072361618320  NOTICE: ActiveAE DSP - starting
22:37:13 T:18446744072361618320   ERROR: int CScriptInvocationManager::ExecuteAsync(const string&, const AddonPtr&, const std::vector<std::basic_string<char> >&) - Not executing non-existing script /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.navi-x/service.py
22:37:13 T:18446744072361618320  NOTICE: initialize done
22:37:13 T:18446744072361618320  NOTICE: Running the application...
22:37:13 T:18446744072361618320  NOTICE: starting zeroconf publishing
22:37:13 T:18446744072361618320  NOTICE: starting upnp client
22:37:13 T:18446744071998794640  NOTICE: ES: Starting UDP Event server on 127.0.0.1:9777
22:37:13 T:18446744071998794640  NOTICE: UDP: Listening on port 9777
22:37:13 T:18446744072361618320  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
22:37:13 T:18446744072361618320  NOTICE: GL_VENDOR = ARM
22:37:13 T:18446744072361618320  NOTICE: GL_RENDERER = Mali-T624
22:37:13 T:18446744072361618320  NOTICE: GL_VERSION = OpenGL ES 3.1
22:37:13 T:18446744072361618320  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.10
22:37:13 T:18446744072361618320  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic
22:37:14 T:18446744072031153040  NOTICE: 1Channel: Service: Installed Version: 2.5.72
22:37:14 T:18446744072031153040  NOTICE: 1Channel: Loading sqlite3 as DB engine
22:37:15 T:18446744072031153040  NOTICE: 1Channel: Service: Resetting...
22:37:15 T:18446744072031153040  NOTICE: 1Channel: Service: starting...
22:37:18 T:18446744072028031888  NOTICE: URLResolver: Initializing URLResolver version: 3.0.23
22:37:19 T:18446744072028031888  NOTICE: Stream All The Sources: Service: Installed Version: 2.0.85
22:37:19 T:18446744072026991504  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': '', 'quality': '0', 'subs': True}"]
22:37:19 T:18446744072026991504  NOTICE: ['SOSAC Service Started']
22:37:19 T:18446744072028031888  NOTICE: Stream All The Sources: Service: starting...
22:37:40 T:18446744072006097808  NOTICE: ['URL: ?cp=736f7361632e7068&list=687474703a2f2f74762e7072656872616a2e6d65']
22:37:40 T:18446744072006097808  NOTICE: ["Running sosac provider with params: {'cp': 'sosac.ph', 'list': 'http://tv.prehraj.me'}"]
22:37:40 T:18446744072006097808  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': '', 'quality': '0', 'subs': True}"]
22:37:40 T:18446744072006097808  NOTICE: ['Examining url http://tv.prehraj.me']
22:37:44 T:18446744072006097808  NOTICE: ['URL: ?cp=736f7361632e7068&list=687474703a2f2f74762e7072656872616a2e6d652f63732f74762d73686f77732d612d7a2f62']
22:37:44 T:18446744072006097808  NOTICE: ["Running sosac provider with params: {'cp': 'sosac.ph', 'list': 'http://tv.prehraj.me/cs/tv-shows-a-z/b'}"]
22:37:44 T:18446744072006097808  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': '', 'quality': '0', 'subs': True}"]
22:37:44 T:18446744072006097808  NOTICE: ['Examining url http://tv.prehraj.me/cs/tv-shows-a-z/b']
22:37:44 T:18446744072006097808  NOTICE: ['Getting shows by letter http://tv.prehraj.me/cs/tv-shows-a-z/b']
22:37:45 T:18446744072006097808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'list' objects
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sosac.ph/default.py", line 47, in <module>
                                                XBMCSosac(SosacContentProvider(reverse_eps=reverse_eps), settings, __addon__).run(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 66, in run
                                                self.list(self.provider.list(params['list']))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 195, in list
                                                return self.list_tv_shows_by_letter(url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.sosac.ph/resources/lib/sosac.py", line 529, in list_tv_shows_by_letter
                                                util.info("Resloved shows " + shows)
                                            TypeError: cannot concatenate 'str' and 'list' objects
                                            -->End of Python script error report<--
22:37:45 T:18446744072361618320   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=687474703a2f2f74762e7072656872616a2e6d652f63732f74762d73686f77732d612d7a2f62
22:37:45 T:18446744072361618320   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=687474703a2f2f74762e7072656872616a2e6d652f63732f74762d73686f77732d612d7a2f62) failed
22:37:48 T:18446744072361618320   ERROR: Unable to activate the previous window
```

**Comment by zbyna** [comment]
Hi,
temporary solution is:
- uninstall sosac 
- download zip files from:
   https://github.com/zbyna/script.module.stream.resolver   and https://github.com/zbyna/plugin.video.sosac.ph
- install these zip files according to the http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files

Final solution will be merging this https://github.com/kodi-czsk/plugin.video.sosac.ph/pull/87  to the main repo

**Comment by okioki13** [comment]
Thanks.
Ip
