### ISSUE TITLE
Not resolve?

### ISSUE THREAD

**Issue by rajcz** [kodi-czsk/plugin.video.sosac.ph#92]
Nevíte někdo co s tímto? Video na webu je ok. Díky

```
['URL: ?play=687474703a2f2f74762e7072656872616a2e6d652f63732f706c617965722f73636f7270696f6e2d73332d653037&cp=736f7361632e7068&title=202d202e2e2e412042696767657220566f7465&']
22:37:57 T:3628  NOTICE: ["Running sosac provider with params: {'play': 'http://tv.prehraj.me/cs/player/scorpion-s3-e07', 'cp': 'sosac.ph', 'title': ' - ...A Bigger Vote'}"]
22:37:57 T:3628  NOTICE: ["Initializing provider sosac.ph with settings {'downloads': 'Z:\\\\SOSAC Repo\\\\', 'quality': '0', 'subs': True}"]
22:37:58 T:3628  NOTICE: ['Found resolvable http://www.streamuj.tv/video/a556cf48e55fbd622b49?remote=1&affid=0&width=960&height=525']
22:37:58 T:3628  NOTICE: [u'Resolving http://www.streamuj.tv/video/a556cf48e55fbd622b49?remote=1&affid=0&width=960&height=525']
22:37:58 T:3628  NOTICE: ["Using resolver 'streamujtv'"]
22:38:00 T:3628   ERROR: Traceback (most recent call last):
22:38:00 T:3628   ERROR:   File "C:\Users\pavel\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\resolver.py", line 68, in resolve
22:38:00 T:3628   ERROR:     value = resolver.resolve(url)
22:38:00 T:3628   ERROR:   File "C:\Users\pavel\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\server\streamujtvresolver.py", line 63, in resolve
22:38:00 T:3628   ERROR:     result.append({'url':stream,'quality':q,'subs':s['link'],'headers':headers,'lang':l})
22:38:00 T:3628   ERROR: KeyError: 'link'
22:38:00 T:3628  NOTICE: ['There was an error resolving http://www.streamuj.tv/video/a556cf48e55fbd622b49?remote=1&affid=0&width=960&height=525']
22:38:02 T:4436   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.sosac.ph/?play=687474703a2f2f74762e7072656872616a2e6d652f63732f706c617965722f73636f7270696f6e2d73332d653037&cp=736f7361632e7068&title=202d202e2e2e412042696767657220566f7465&]
22:38:06 T:1736  NOTICE: 
```

**Comment by lubo** [comment]
Pouzivas najnovsiu verziu stream resolveru ?

**Comment by rajcz** [comment]
Ano

**Comment by ghost** [comment]
uz to ide s najnovsim resolverom moze sa to zavrieť
