### ISSUE TITLE
nefungujuci katalog filmov a serialov

### ISSUE THREAD

**Issue by igerko** [kodi-czsk/plugin.video.sosac.ph#97]
Ked sa pokusam otvorit sosac dostavam error a nevidim ziadny zoznam filmov ani serialov.

> 21:03:49 T:1092  NOTICE: ['URL: ?cp=736f7361632e7068&list=687474703a2f2f6d6f766965732e7072656872616a2e6d652f66696c6d79786d6c7069736d656e6f2e7068703f7069736d656e6f3d64']
21:03:49 T:1092  NOTICE: ["Running sosac provider with params: {'cp': 'sosac.ph', 'list': 'http://movies.prehraj.me/filmyxmlpismeno.php?pismeno=d'}"]
21:03:49 T:1092  NOTICE: ["Initializing provider sosac.ph with settings {'lang': '0', 'downloads': '', 'quality': '0', 'subs': True}"]
21:03:49 T:1092  NOTICE: ['Examining url http://movies.prehraj.me/filmyxmlpismeno.php?pismeno=d']
21:03:49 T:1092   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xml.etree.ElementTree.ParseError'>
                                            Error Contents: undefined entity: line 61, column 65
                                            Traceback (most recent call last):
                                              File "C:\Users\Jakub Kacur\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\default.py", line 47, in <module>
                                                XBMCSosac(SosacContentProvider(reverse_eps=reverse_eps), settings, __addon__).run(params)
                                              File "C:\Users\Jakub Kacur\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\contentprovider\xbmcprovider.py", line 70, in run
                                                self.list(self.provider.list(params['list']))
                                              File "C:\Users\Jakub Kacur\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 203, in list
                                                return self.list_xml_letter(url)
                                              File "C:\Users\Jakub Kacur\AppData\Roaming\Kodi\addons\plugin.video.sosac.ph\resources\lib\sosac.py", line 224, in list_xml_letter
                                                tree = ET.fromstring(data)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1300, in XML
                                                parser.feed(text)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1642, in feed
                                                self._raiseerror(v)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
                                                raise err
                                            ParseError: undefined entity: line 61, column 65
                                            -->End of Python script error report<--
21:03:49 T:6712   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=687474703a2f2f6d6f766965732e7072656872616a2e6d652f66696c6d79786d6c7069736d656e6f2e7068703f7069736d656e6f3d64
21:03:49 T:6712   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sosac.ph/?cp=736f7361632e7068&list=687474703a2f2f6d6f766965732e7072656872616a2e6d652f66696c6d79786d6c7069736d656e6f2e7068703f7069736d656e6f3d64) failed
21:03:49 T:3876  NOTICE: ['URL: ?cp=736f7361632e7068&list=687474703a2f2f6d6f766965732e7072656872616a2e6d65']
21:03:49 T:3876  NOTICE: ["Running sosac provider with params: {'cp': 'sosac.ph', 'list': 'http://movies.prehraj.me'}"]
21:03:49 T:3876  NOTICE: ["Initializing provider sosac.ph with settings {'lang': '0', 'downloads': '', 'quality': '0', 'subs': True}"]
21:03:49 T:3876  NOTICE: ['Examining url http://movies.prehraj.me']

**Comment by lubo** [comment]
Vid. #96.
